package com.car.domain;
// Generated 2017-5-4 20:49:12 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Personcar generated by hbm2java
 */
@Entity
@Table(name = "personcar", catalog = "car")
public class Personcar implements java.io.Serializable {

	private Integer id;
	private Person person;
	private String carType;
	private String licensePlate;	//车牌号
	private String licenseType;		//车牌类型
	private String engineNumber;	//发动机号
	private int state;
	
	
	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Personcar() {
	}

	public Personcar(int state,Person person, String carType, String licensePlate, String licenseType, String engineNumber) {
		this.person = person;
		this.state = state;
		this.carType = carType;
		this.licensePlate = licensePlate;
		this.licenseType = licenseType;
		this.engineNumber = engineNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "personID", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "carType", nullable = false, length = 50)
	public String getCarType() {
		return this.carType;
	}

	public void setCarType(String carType) {
		this.carType = carType;
	}

	@Column(name = "licensePlate", nullable = false, length = 50)
	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	@Column(name = "licenseType", nullable = false, length = 50)
	public String getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(String licenseType) {
		this.licenseType = licenseType;
	}

	@Column(name = "engineNumber", nullable = false, length = 50)
	public String getEngineNumber() {
		return this.engineNumber;
	}

	public void setEngineNumber(String engineNumber) {
		this.engineNumber = engineNumber;
	}

}
