package com.car.domain;
// Generated 2017-5-4 20:49:12 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Point generated by hbm2java
 */
@Entity
@Table(name = "point", catalog = "car")
public class Point implements java.io.Serializable {

	private Integer id;
	private double pointX;
	private double pointY;

	public Point() {
	}

	public Point(double pointX, double pointY) {
		this.pointX = pointX;
		this.pointY = pointY;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "point_x", nullable = false, precision = 22, scale = 0)
	public double getPointX() {
		return this.pointX;
	}

	public void setPointX(double pointX) {
		this.pointX = pointX;
	}

	@Column(name = "point_y", nullable = false, precision = 22, scale = 0)
	public double getPointY() {
		return this.pointY;
	}

	public void setPointY(double pointY) {
		this.pointY = pointY;
	}



}
