package com.car.domain;
// Generated 2017-5-4 20:49:12 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name = "store", catalog = "car")
public class Store implements java.io.Serializable {

	private Integer id;
	private String city;
	private String name;
	private String address;
	private String phoneNumber;
	private String description;
	private String isPass;
	private Person owener;
	private int state;
	private Set<Storeproduct> storeproducts = new HashSet<Storeproduct>(0);
	private Set<Storeorder> storeorders = new HashSet<Storeorder>(0);

	
	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Store() {
	}

	public Store(int state,String city, String name, Person owener,String address, String phoneNumber, String description, String isPass) {
		this.city = city;
		this.state = state;
		this.name = name;
		this.owener = owener;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.description = description;
		this.isPass = isPass;
	}

	public Store(String city, String name, Person owener, String address, String phoneNumber, String description, String isPass,
			Set<Storeproduct> storeproducts,
			 Set<Storeorder> storeorders) {
		this.city = city;
		this.name = name;
		this.owener = owener;
		this.address = address;
		this.phoneNumber = phoneNumber;
		this.description = description;
		this.isPass = isPass;
		this.storeproducts = storeproducts;
		this.storeorders = storeorders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phoneNumber", nullable=false, length=15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "isPass", nullable = false, length = 2)
	public String getIsPass() {
		return this.isPass;
	}

	public void setIsPass(String isPass) {
		this.isPass = isPass;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "store")
	public Set<Storeproduct> getStoreproducts() {
		return this.storeproducts;
	}

	public void setStoreproducts(Set<Storeproduct> storeproducts) {
		this.storeproducts = storeproducts;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "store")
	public Set<Storeorder> getStoreorders() {
		return this.storeorders;
	}

	public void setStoreorders(Set<Storeorder> storeorders) {
		this.storeorders = storeorders;
	}
	
	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="owenerId")
	public void setOwener(Person owener){
		this.owener = owener;
	}
	public Person getOwener(){
		return this.owener;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	
}
